---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
spec:
  project: default
  source:
    chart: applications
    repoURL: https://stopdenbus.github.io/helm-charts
    targetRevision: 0.0.91
    helm:
      releaseName: applications
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
