apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-bootstrap
spec:
  project: cluster-bootstrap
  source:
    repoURL: git@github.com:StopDenBus/argocd.git
    targetRevision: HEAD
    path: app-resources/cluster-bootstrap
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gusek.info
spec:
  project: gusek.info
  source:
    repoURL: git@github.com:StopDenBus/argocd.git
    targetRevision: HEAD
    path: app-resources/gusek.info
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      
{{- range $app, $properties := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app }}
spec:
  project: {{ $properties.project }}
  source:
    chart: {{ $properties.chart }}
    repoURL: {{ include "repoURL" $properties }}
    targetRevision: {{ $properties.targetRevision }}
    {{- if $properties.helm }}
    {{- include "helmParameters" $properties | nindent 4 }}
    {{- end }}
  destination:
    namespace: {{ $properties.namespace }}
    server: https://kubernetes.default.svc
  {{- include "syncPolicy" $properties | nindent 2 }}  
{{- end }}