apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-ssh-key
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-ssh-key
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds    
      type: Opaque
      data:
        sshPrivateKey: "{{ `{{ .sshPrivateKey | toString }}` }}"
        type: git
        url: "{{ `{{ .githubRepo | toString }}` }}"
    creationPolicy: Owner
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: secrets/data/kubernetes/argocd/sshPrivateKey
        property: key
    - secretKey: githubRepo
      remoteRef:
        key: secrets/data/kubernetes/argocd/githubRepo
        property: key    
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    template:
      type: Opaque
      data:
        admin.password: "{{ `{{ .password | toString }}` }}"
        admin.passwordMtime: "{{ `{{ .passwordMtime | toString }}` }}"
        oidc.clientSecret: "{{ `{{ .oidcClientSecret | toString }}` }}"
        server.secretkey: "{{ `{{ .serverSecretKey | toString }}` }}"
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: secrets/data/kubernetes/argocd/admin
        property: password
    - secretKey: passwordMtime
      remoteRef:
        key: secrets/data/kubernetes/argocd/admin
        property: passwordMtime
    - secretKey: oidcClientSecret
      remoteRef:
        key: secrets/data/kubernetes/dex/clients/argocd
        property: key
    - secretKey: serverSecretKey
      remoteRef:
        key: secrets/data/kubernetes/argocd/server/secretkey
        property: key        