apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-admin-password
    template:
      type: Opaque
      data:
        admin-password: "{{ `{{ .admin_password | toString }}` }}"
        admin-user: admin   
    creationPolicy: Owner
  data:
    - secretKey: admin_password
      remoteRef:
        key: secrets/data/kubernetes/grafana/admin
        property: key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oidc
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-oidc
    template:
      type: Opaque
      data:
        clientSecret: "{{ `{{ .oidcClientSecret | toString }}` }}"
    creationPolicy: Owner
  data:
    - secretKey: oidcClientSecret
      remoteRef:
        key: secrets/data/kubernetes/dex/clients/grafana
        property: key
        