---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-mailu-secrets
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mysql-mailu-secrets
    template:
      type: Opaque
      data:
        mysql-mailu-database: "mailu"
        mysql-mailu-password: "{{ `{{ .mailu_password | toString }}` }}"
        mysql-mailu-username: "mailu"
    creationPolicy: Owner
  data:
    - secretKey: mailu_password
      remoteRef:
        key: secrets/data/mysql/mailu
        property: key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mailu-secret-key
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mailu-secret-key
    template:
      type: Opaque
      data:
        secret-key: "{{ `{{ .secret_key | toString }}` }}"
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: secrets/data/kubernetes/mailu/secret_key
        property: key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mailu-admin-secret
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mailu-admin-secret
    template:
      type: Opaque
      data:
        password: "{{ `{{ .password | toString }}` }}"
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: secrets/data/kubernetes/mailu/admin
        property: key        
      