apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs
parameters:
  recordsize: "4k"
  compression: "on"
  dedup: "off"
  fstype: "zfs"
  poolname: "rpool/kubernetes"
provisioner: zfs.csi.openebs.io