apiVersion: v1
kind: Secret
metadata:
  name: ldap-password
  annotations:
    avp.kubernetes.io/path: "secrets/data/ldap/dex"
type: Opaque
data:
  LDAP_PASSWORD: <key | base64encode>
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-client-secret
  annotations:
    avp.kubernetes.io/path: "secrets/data/kubernetes/dex/clients/argocd"
type: Opaque
data:
  client-id: {{ print "argocd" | b64enc }}
  client-secret: <key | base64encode>