apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ldap-password
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ldap-password
    creationPolicy: Owner
  data:
    - secretKey: LDAP_PASSWORD
      remoteRef:
        key: secrets/data/ldap/dex
        property: key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-client-secret
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-client-secret
    template:
      type: Opaque
      data:
        client-id: argocd
        client-secret: "{{ `{{ .client_secret | toString }}` }}"
    creationPolicy: Owner
  data:
    - secretKey: client_secret
      remoteRef:
        key: secrets/data/kubernetes/dex/clients/argocd
        property: key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-client-secret
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault-client-secret
    template:
      type: Opaque
      data:
        client-id: vault
        client-secret: "{{ `{{ .client_secret | toString }}` }}"
    creationPolicy: Owner
  data:
    - secretKey: client_secret
      remoteRef:
        key: secrets/data/kubernetes/dex/clients/vault
        property: key
 ---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: google-client
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: google-client
    template:
      type: Opaque
      data:
        client-id: "{{ `{{ .client_id | toString }}` }}"
        client-secret: "{{ `{{ .client_secret | toString }}` }}"
        service-account-file: "{{ `{{ .service_account | toString }}` }}"
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: secrets/data/kubernetes/dex/google
        property: clientID
    - secretKey: client_secret
      remoteRef:
        key: secrets/data/kubernetes/dex/google
        property: clientSecret
    - secretKey: service_account
      remoteRef:
        key: secrets/data/kubernetes/dex/google
        property: serviceAccount         
      