nginx:
  fullnameOverride: nginx-ingress
  controller:
    extraArgs:
      default-ssl-certificate: "ingress-nginx/wildcard-apps"
      enable-ssl-passthrough: true
    hostNetwork: false
    ingressClassResource:
      default: true
    updateStrategy:
      type: Recreate
  