istio-base:
  profile: ambient

istio-istiod:
  profile: ambient

istio-cni:
  profile: ambient

istio-gateway:
  profile: ambient
  service:
    type: Loadbalancer
    ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443

istio-ztunnel:
  profile: ambient