istio-base:
  profile: ambient

istio-istiod:
  profile: ambient

istio-cni:
  profile: ambient

istio-gateway:
  name: "ingress"
  labels:
    app: istio-ingressgateway
    istio: ingressgateway  

  profile: ambient
  service:
    type: LoadBalancer
    ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443

istio-ztunnel:
  profile: ambient

istio_config:
  serviceEntries:
    - name: vault
      hosts:
        - vault.gusek.info
      ports:
        - name: https
          number: 443
          protocol: HTTPS
      resolution: DNS
      location: MESH_EXTERNAL
