
## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []

## @section Common parameters
##

## PHP hello world image version
## ref: https://github.com/StopDenBus/php_hello_world/pkgs/container/php_hello_world%2Fphp-hello-world
## @param image.registry Hello World image registry
## @param image.repository Hello World Image name
## @param image.tag Hello World Image tag
## @param image.digest Hello World image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag
## @param image.pullPolicy Hello World image pull policy
## @param image.pullSecrets Specify docker-registry secret names as an array
##
image:
  registry: ghrc.io
  repository: stopdenbus/php_hello_world/php-hello-world
  tag: 0.0.18
  digest: ""
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## e.g:
  ## pullSecrets:
  ##   - myRegistryKeySecretName
  ##
  pullSecrets: []
  ## Set to true if you would like to see extra information on logs
  ##