apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wishlist-backend.fullname" . }}-database-config
  labels:
    {{- include "wishlist-backend.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.config }}
  {{- if ne $key "databasePassword" }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
