{{- if not (.Values.config.databasePassword).existingSecret}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "wishlist-backend.databaseSecret" . }}
  labels:
    {{- include "wishlist-backend.labels" . | nindent 4 }}
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ include "wishlist-backend.databaseSecret" . }}
    template:  
      type: Opaque
      data:
        database-password: "{{ `{{ .database_password | toString }}` }}"
    creationPolicy: Owner
  data:
    - secretKey: database_password
      remoteRef:
        key: {{ include "wishlist-backend.vaultKey" . }}
        property: {{ include "wishlist-backend.vaultProperty" . }}
{{- end }}