loki:
  config:
    limits_config:
      per_stream_rate_limit: 5M
      per_stream_rate_limit_burst: 20M    
  ingress:
    enabled: true
    annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: loki.apps.gusek.info
        paths:
          write:
            - /api/prom/push
            - /loki/api/v1/push
          read:
            - /api/prom/tail
            - /loki/api/v1/tail
            - /loki/api
            - /api/prom/rules
            - /loki/api/v1/rules
            - /prometheus/api/v1/rules
            - /prometheus/api/v1/alerts
          singleBinary:
            - /api/prom/push
            - /loki/api/v1/push
            - /api/prom/tail
            - /loki/api/v1/tail
            - /loki/api
            - /api/prom/rules
            - /loki/api/v1/rules
            - /prometheus/api/v1/rules
            - /prometheus/api/v1/alerts      
    tls:
      - hosts:
        - loki.apps.gusek.info
        secretName: wildcard-apps    
  persistence:
    enabled: true
    storageClassName: zfs
  rbac:
    pspEnabled: false
  service:
    type: NodePort
    nodePort: 31000
  



