loki:
  config:
    limits_config:
      per_stream_rate_limit: 5M
      per_stream_rate_limit_burst: 20M
  persistence:
    enabled: true
    storageClassName: zfs
  rbac:
    pspEnabled: false
  service:
    type: NodePort
    nodePort: 31000
  



