loki:
  config:
    limits_config:
      per_stream_rate_limit: 5M
      per_stream_rate_limit_burst: 20M    
  ingress:
    enabled: true
    annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: loki.apps.gusek.info
        paths:
          - /
    tls:
      - hosts:
        - loki.apps.gusek.info
        secretName: wildcard-apps    
  persistence:
    enabled: true
    storageClassName: zfs
  rbac:
    pspEnabled: false
  service:
    type: NodePort
    nodePort: 31000
  



