apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wishlist-frontend.fullname" . }}
  labels:
    {{- include "wishlist-frontend.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}