---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-secrets
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mariadb-secrets
    template:
      type: Opaque
      data:
        mariadb-root-password: "{{ `{{ .root_password | toString }}` }}"
    creationPolicy: Owner
  data:
    - secretKey: root_password
      remoteRef:
        key: secrets/data/mysql/admin
        property: key
      