---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-secrets
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pihole-secrets
    template:
      type: Opaque
      data:
        pihole-admin-password: "{{ `{{ .root_password | toString }}` }}"
    creationPolicy: Owner
  data:
    - secretKey: root_password
      remoteRef:
        key: secrets/data/pihole/admin
        property: key
      