apiVersion: v1
kind: ConfigMap
metadata:
  name: named
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: named
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  named.conf: |
    include "/etc/bind/named-acls.conf";
    include "/etc/bind/named.conf.options";
    include "/etc/bind/named.conf.local";
    include "/etc/bind/named.conf.zones";
    include "/etc/bind/named-keys.conf";
  named-acls.conf: |
    acl internals { 127.0.0.0/8; 192.168.0.0/24; };
  named.conf.options: |
    options {
          directory "/var/bind";
          version "Go Away 0.0.7";
          notify no;
          empty-zones-enable no;
          auth-nxdomain yes;
          forwarders { 8.8.8.8; 8.8.4.4; };
          allow-transfer { none; };

          dnssec-validation no;
          
          // If you only use IPv4. 
          listen-on-v6 { none; };
          // listen on these ipnumbers. 
          listen-on port 53 { any; };

          // Added Per Debian buster Bind9. 
          // Due to : resolver: info: resolver priming query complete messages in the logs. 
          // See: https://gitlab.isc.org/isc-projects/bind9/commit/4a827494618e776a78b413d863bc23badd14ea42
          minimal-responses yes;

          //  Add any subnets or hosts you want to allow to use this DNS server
          allow-query { "internals";  };
          allow-query-cache { "internals"; };

          //  Add any subnets or hosts you want to allow to use recursive queries
          recursion yes;
          allow-recursion {  "internals"; };

          // https://wiki.samba.org/index.php/Dns-backend_bind
          // DNS dynamic updates via Kerberos (optional, but recommended)
          // ONE of the following lines should be enabled AFTER you provision or join a DC with bind9_dlz 
          // or AFTER upgrading your dns from internal to bind9_dlz 
          // Before Samba 4.9.0
          // tkey-gssapi-keytab "/var/lib/samba/private/dns.keytab";
          // From Samba 4.9.0 ( You will need to run samba_upgradedns if upgrading your Samba version. ) 
          // tkey-gssapi-keytab "/var/lib/samba/bind-dns/dns.keytab";
      };
  named.conf.local: |
    // include "/var/lib/samba/bind-dns/named.conf";
  named.conf.zones: |
    // prime the server with knowledge of the root servers
    zone "." {
      type hint;
      file "/var/bind/named.root";
    };

    // be authoritative for the localhost forward and reverse zones, and for
    // broadcast zones as per RFC 1912

    zone "localhost" {
            type master;
            file "/etc/bind/db.local";
    };

    zone "127.in-addr.arpa" {
            type master;
            file "/etc/bind/db.127";
    };

    zone "0.in-addr.arpa" {
            type master;
            file "/etc/bind/db.0";
    };

    zone "255.in-addr.arpa" {
            type master;
            file "/etc/bind/db.255";
    };

    zone "apps.gusek.info" {
      type master;
      file "/var/bind/db.apps.gusek.info";
      allow-transfer {
        key "externaldns";
      };
      update-policy {
        grant externaldns zonesub ANY;
      };
    };
  db.local: |
    ;
    ; BIND data file for local loopback interface
    ;
    $TTL    604800
    @       IN      SOA     localhost. root.localhost. (
                                  2         ; Serial
                            604800         ; Refresh
                              86400         ; Retry
                            2419200         ; Expire
                            604800 )       ; Negative Cache TTL
    ;
    @       IN      NS      localhost.
    @       IN      A       127.0.0.1
    @       IN      AAAA    ::1
  db.127: |
    ;
    ; BIND reverse data file for local loopback interface
    ;
    $TTL    604800
    @       IN      SOA     localhost. root.localhost. (
                                  1         ; Serial
                            604800         ; Refresh
                              86400         ; Retry
                            2419200         ; Expire
                            604800 )       ; Negative Cache TTL
    ;
    @       IN      NS      localhost.
    1.0.0   IN      PTR     localhost.
  db.0: |
    ;
    ; BIND reverse data file for "this host on this network" zone
    ;
    $TTL    604800
    @       IN      SOA     localhost. root.localhost. (
                                  1         ; Serial
                            604800         ; Refresh
                              86400         ; Retry
                            2419200         ; Expire
                            604800 )       ; Negative Cache TTL
    ;
    @       IN      NS      localhost.
  db.255: |
    ;
    ; BIND reverse data file for broadcast zone
    ;
    $TTL    604800
    @       IN      SOA     localhost. root.localhost. (
                                  1         ; Serial
                            604800         ; Refresh
                              86400         ; Retry
                            2419200         ; Expire
                            604800 )       ; Negative Cache TTL
    ;
    @       IN      NS      localhost.
  db.apps.gusek.info: |
    $ORIGIN .
    $TTL 604800     ; 1 week
    apps.gusek.info         IN SOA  apps.gusek.info. root.apps.gusek.de. (
                                    25         ; serial
                                    60         ; refresh (1 minute)
                                    60         ; retry (1 minute)
                                    60         ; expire (1 minute)
                                    60         ; minimum (1 minute)
                                    )
                            NS      samba.gusek.info.
    $ORIGIN apps.gusek.info.
    $TTL 600        ; 10 minutes
    *                       A       192.168.0.10
    $TTL 604800     ; 1 week
    ns                      A       192.168.0.2