apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: named-key-secret
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: named-key-secret
    template:
      type: Opaque
      data:
        named-keys.conf: |
          key "externaldns" {
                  algorithm hmac-sha256;
                  secret "{{ `{{ .key | toString }}` }}";
          };
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: secrets/data/samba/tsig
        property: key