# Default values for wishlist-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  # mysql or pgsql
  databaseType: mysql
  databaseHost: mysql.mysql.svc.cluster.local
  databasePort: 3306
  databaseName: wishlist
  databaseUser: wishlist
  databasePassword: {}
    # # get password from hashicorp vault
    # vaultProperty: key
    # vaultKey: secrets/data/mysql/wishlist
    # # use existing secret
    # existingSecret: mySecret
    # existingSecretKey: database-password

replicaCount: 1

image:
  repository: ghcr.io/stopdenbus/wishlist-backend/wishlist-backend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.0.11"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1001

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1001

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: wishlist-backend.apps.gusek.info
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
      - wishlist-backend.apps.gusek.info
      secretName: wildcard-apps

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
