---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tsig-secrets
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: tsig-secrets
    template:
      type: Opaque
      data:
        rfc2136_tsig_secret: "{{ `{{ .tsig_secret | toString }}` }}"
    creationPolicy: Owner
  data:
    - secretKey: tsig_secret
      remoteRef:
        key: secrets/data/samba/tsig
        property: key