apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: renovate-env
    template:
      type: Opaque
      data:
        RENOVATE_TOKEN: "{{ `{{ .renovate_token | toString }}` }}"
    creationPolicy: Owner
  data:
    - secretKey: renovate_token
      remoteRef:
        key: secrets/data/kubernetes/renovate
        property: codeberg_token
