name: Increase chart versions

on:
  pull_request:
    types: [ closed ]
  # push:
  #   branches:
  #     - feature/test_workflow  
  workflow_dispatch:

jobs:
  checkout:
    #if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.DEPLOY_TOKEN }}

  getChangedFolders:
    runs-on: ubuntu-latest
    needs: checkout
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.DEPLOY_TOKEN }}
      - uses: tj-actions/changed-files@v45
        id: get_changed
        with:
          dir_names: "true"
          json: "true"
          json_raw_format: true
          files: charts/**
      - id: matrix
        run: |
          echo "matrix=${{ steps.get_changed.outputs.all_changed_files}}" >> $GITHUB_OUTPUT

  increase_chart_version:
    runs-on: ubuntu-latest
    needs: getChangedFolders
    strategy:
      matrix:
        value: ${{ fromJson(needs.getChangedFolders.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.DEPLOY_TOKEN }}
          ref: main

      - run: |
          echo "Increase chart version for chart: ${{ matrix.value }}"
          yq '.version |= (split(".") | .[-1] |= ((. tag = "!!int") + 1) | join("."))' -i ${{ matrix.value }}/Chart.yaml

      - name: Configure Git
        run: |
          git config  --local user.name "$GITHUB_ACTOR"
          git config  --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am "Bump chart version"

      - name: Push to main
        run: |
          git push origin main
