name: Release Charts

on:
  workflow_run:
    workflows:
      - Increase chart versions
    types:
      - completed  
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    needs: increase_chart_version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"