apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: nginx
spec:
  addresses:
    - 192.168.0.11/32
  serviceAllocation:
    priority: 50
    namespaces:
      - ingress-nginx
      - pihole
    serviceSelectors:
      - matchExpressions:
          - {key: app.kubernetes.io/name, operator: In, values: [nginx, pihole]}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: mail
spec:
  addresses:
    - 192.168.0.12/32
  serviceAllocation:
    priority: 50
    namespaces:
      - mail
    serviceSelectors:
      - matchExpressions:
          - {key: app.kubernetes.io/name, operator: In, values: [mailu]}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: samba
spec:
  addresses:
    - 192.168.0.13/32
  serviceAllocation:
    priority: 50
    namespaces:
      - samba
    serviceSelectors:
      - matchExpressions:
          - {key: app.kubernetes.io/name, operator: In, values: [samba]}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: istio
spec:
  addresses:
  - 192.168.0.20/32
  serviceAllocation:
    priority: 50
    namespaces:
      - istio-system
    serviceSelectors:
      - matchExpressions:
          - {key: app, operator: In, values: [istio-ingressgateway]}
